version: '3.8'

services:
  namenode:
    image: apache/hadoop:3.4.1
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"
      - "8020:8020"
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - hadoop_namenode:/opt/hadoop/dfs/name
      - ./data:/data
      - ./scripts:/scripts
      - ./config:/opt/hadoop/etc/hadoop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 30s
      timeout: 10s
      retries: 3

  datanode:
    image: apache/hadoop:3.4.1
    hostname: datanode
    command: ["hdfs", "datanode"]
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - hadoop_datanode:/opt/hadoop/dfs/data
      - ./data:/data
      - ./scripts:/scripts
      - ./config:/opt/hadoop/etc/hadoop
    depends_on:
      - namenode

  resourcemanager:
    image: apache/hadoop:3.4.1
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - "8088:8088"
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./config:/opt/hadoop/etc/hadoop
    depends_on:
      - namenode
      - datanode

  nodemanager:
    image: apache/hadoop:3.4.1
    hostname: nodemanager
    command: ["yarn", "nodemanager"]
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./config:/opt/hadoop/etc/hadoop
    depends_on:
      - resourcemanager

  historyserver:
    image: apache/hadoop:3.4.1
    hostname: historyserver
    command: ["mapred", "historyserver"]
    ports:
      - "19888:19888"
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./config:/opt/hadoop/etc/hadoop
    depends_on:
      - namenode

volumes:
  hadoop_namenode:
  hadoop_datanode:
